# 27/04 - Pair Programming Pandas VII - Tatiana & Lara

In [26]:
import pandas as pd
import numpy as np
import re

# Ejercicio 1 
Cread una columna nueva y una funciÃ³n que nos el mes donde ocurriÃ³ el ataque. Tened en cuenta que no todos las filas tienen la misma estructura y que puede que no haya la informaciÃ³n de mes. En ese caso devolved un nulo (NaN).
ðŸ’¡ Pista ðŸ’¡PodÃ©is usar regex.

In [19]:
df = pd.read_csv("/mnt/c/Users/USUARIO/Desktop/Adalab/DA-promo-A-module-2-pairprog-1-pair-1-Tatiana_Lara/PANDAS/6_Pandas/union_ataques.csv")
df.head()

,Unnamed: 0,Case Number,Year,Type,Country,Area,Location,Activity,Name,Sex,...,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal (Y/N),Injury,Date
0,0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018
1,1,2018.06.18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,N,Minor injury to left thigh,18-Jun-2018
2,2,2018.06.09,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,N,Injury to left lower leg from surfboard skeg,09-Jun-2018
3,3,2018.06.08,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,N,Minor injury to lower leg,08-Jun-2018
4,4,2018.06.04,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,N,Lacerations to leg & hand shark PROVOKED INCIDENT,04-Jun-2018

In [21]:
patron = r'\b\w{3}\b'

string = "25-Jun-2018"

In [22]:
re.findall(patron, string)

['Jun']

In [23]:
def sacar_mes(col):
    patron = r'\b\w{3}\b'
    try:
        return re.findall(patron, col)[0]
    except:
        return np.nan

#Ejercicio 2 
Vamos con la columna fatal_(y/n). Lo primero que tenÃ©is que hacer es evaluar los valores Ãºnicos que hay. EsperarÃ­amos tener solo dos valores: y y n, pero tristemente no es asÃ­ ðŸ˜­. Cread una columna nueva y una funciÃ³n que devuelva unicamente y o n y que devuelva un nulo (NaN) si no se encuentra el valor.

In [25]:
df["Fatal (Y/N)"].value_counts()

N          4284
Y          1385
UNKNOWN      71
 N            7
M             1
2017          1
N             1
y             1
Name: Fatal (Y/N), dtype: int64

In [29]:
df_copia= df.copy()
df_copia

,Unnamed: 0,Case Number,Year,Type,Country,Area,Location,Activity,Name,Sex,...,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Fatal (Y/N),Injury,Date
0,0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018
1,1,2018.06.18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,N,Minor injury to left thigh,18-Jun-2018
2,2,2018.06.09,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,N,Injury to left lower leg from surfboard skeg,09-Jun-2018
3,3,2018.06.08,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,N,Minor injury to lower leg,08-Jun-2018
4,4,2018.06.04,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,N,Lacerations to leg & hand shark PROVOKED INCIDENT,04-Jun-2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6283,6283,ND.0001,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Y,"FATAL. ""Shark bit him in half, carrying away t...",1845-1853
6284,6284,2017.01.08.R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No attack, shark made a threat display",Reported 08-Jan-2017
6285,6285,1836.08.19.R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,FATAL,Reported 19-Aug-1836
6286,6286,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6287,6287,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
def yes_no(columna):
    if (columna == "Y") or (columna == "y"): 
        return "Y"
    elif (columna == "N") or (columna==" N")| (columna=="N "):
        return "N"
    else:
        return np.nan

In [ ]:
df_copia["fatal limpia"] =(df_copia["Fatal (Y/N)"].apply(yes_no))
df_copia